/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Very Simple Books API
 * A simple books API
 * OpenAPI spec version: 1.0
 */

export interface CreateBookDto {
  title: string;
  author: string;
  year: number;
}
