/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Very Simple Books API
 * A simple books API
 * OpenAPI spec version: 1.0
 */

export * from './book';
export * from './createBookDto';
export * from './updateBookDto';